using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using Autodesk.Revit.Attributes;
using CsvHelper;
using CsvHelper.Configuration;
using System.Globalization;

namespace CEDDSlopeModeler
{
    // A simple DTO to hold rows from the Dynamo-generated CSVs
    public class ExtractedPoint
    {
        public double X { get; set; }
        public double Y { get; set; }
        public double Z { get; set; }
        public double RotationAngle { get; set; }
        // Dynamo scripts applied a "Hole Dia" string param to soil nails and length to U-channels.
        public string ParameterValue { get; set; } 
    }

    [Transaction(TransactionMode.Manual)]
    public class Command : IExternalCommand
    {
        public Result Execute(
            ExternalCommandData commandData, 
            ref string message, 
            ElementSet elements)
        {
            // Get application and document objects
            UIApplication uiapp = commandData.Application;
            Document doc = uiapp.ActiveUIDocument.Document;

            // Step 1: Prompt user for the path to the CSV file (generated by Civil 3D extract or web app)
            // and the type of object to generate.
            // Using a simple file dialog or reading a hardcoded path for the prototype:
            string csvFilePath = @"C:\Path\To\extracted_points.csv"; 
            string familyFilePath = @"C:\Path\To\CEDDSlopeModeler\Families\19_SON-TYP-CSH-___-___.rfa"; 
            string familySymbolName = "Nail Head_400x400"; // Example symbol name for Soil Nail

            if (!File.Exists(csvFilePath))
            {
                TaskDialog.Show("CEDD Slope Modeler", 
                    "Could not find the coordinates CSV file. In a real environment, allow user to browse.");
                return Result.Cancelled;
            }

            // Step 2: Read CSV file
            List<ExtractedPoint> points = ReadCsv(csvFilePath);
            if (points == null || points.Count == 0)
            {
                TaskDialog.Show("CEDD Slope Modeler", "No valid points found in the CSV.");
                return Result.Failed;
            }

            // Step 3: Start Revit Transaction
            using (Transaction trans = new Transaction(doc, "Generate CEDD BIM Models"))
            {
                trans.Start();

                // 3a. Ensure the Family is loaded
                FamilySymbol familySymbol = GetOrLoadFamilySymbol(doc, familyFilePath, familySymbolName);
                if (familySymbol == null)
                {
                    message = "Could not find or load the required CEDD Family Symbol.";
                    trans.RollBack();
                    return Result.Failed;
                }

                // 3b. Loop through points to place instances
                int count = 0;
                foreach (var pt in points)
                {
                    // Create XYZ for location
                    // Note: Revit internal units are decimal feet, conversion from meters or mm might be required.
                    // Assuming input is in meters; 1 m = 3.28084 feet.
                    double conversionToFeet = 3.28084;
                    XYZ location = new XYZ(pt.X * conversionToFeet, pt.Y * conversionToFeet, pt.Z * conversionToFeet);

                    // Place the Family Instance
                    FamilyInstance instance = doc.Create.NewFamilyInstance(
                        location, 
                        familySymbol, 
                        Autodesk.Revit.DB.Structure.StructuralType.NonStructural);

                    // Replicate the Dynamo Script action: Element.SetParameterByName and FamilyInstance.SetRotation
                    
                    // Rotation
                    if (pt.RotationAngle != 0)
                    {
                        Line axis = Line.CreateBound(location, location + XYZ.BasisZ);
                        ElementTransformUtils.RotateElement(doc, instance.Id, axis, pt.RotationAngle);
                    }

                    // Set custom parameters (like Dynamo does with "Hole Dia" = 100, etc.)
                    if (!string.IsNullOrEmpty(pt.ParameterValue))
                    {
                        Parameter param = instance.LookupParameter("Hole Dia");
                        if (param != null && !param.IsReadOnly)
                        {
                            param.Set(pt.ParameterValue);
                        }
                    }

                    count++;
                }

                trans.Commit();
                TaskDialog.Show("Success", $"Successfully generated {count} CEDD BIM models.");
            }

            return Result.Succeeded;
        }

        private List<ExtractedPoint> ReadCsv(string filePath)
        {
            try
            {
                using (var reader = new StreamReader(filePath))
                using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
                {
                    // For demo purposes, we do not require a strict header layout. 
                    // Assume columns: X, Y, Z, RotationAngle, ParameterValue
                    csv.Context.RegisterClassMap<ExtractedPointMap>();
                    return csv.GetRecords<ExtractedPoint>().ToList();
                }
            }
            catch(Exception e)
            {
                TaskDialog.Show("CSV Error", "Error reading CSV: " + e.Message);
                return null;
            }
        }

        private FamilySymbol GetOrLoadFamilySymbol(Document doc, string rfaPath, string symbolName)
        {
            // Check if it already exists
            FilteredElementCollector collector = new FilteredElementCollector(doc)
                .OfClass(typeof(FamilySymbol));

            foreach (FamilySymbol symbol in collector)
            {
                if (symbol.Name == symbolName)
                {
                    if (!symbol.IsActive) symbol.Activate();
                    return symbol;
                }
            }

            // Not found, attempt to load the family
            if (doc.LoadFamily(rfaPath, out Family family))
            {
                // Find the specific symbol within the newly loaded family
                ISet<ElementId> symbolIds = family.GetFamilySymbolIds();
                foreach (ElementId id in symbolIds)
                {
                    FamilySymbol symbol = doc.GetElement(id) as FamilySymbol;
                    if (symbol != null && symbol.Name == symbolName)
                    {
                        if (!symbol.IsActive) symbol.Activate();
                        return symbol;
                    }
                }
                
                // If specific symbol name not found, grab the first one
                ElementId firstId = symbolIds.FirstOrDefault();
                if (firstId != ElementId.InvalidElementId)
                {
                    FamilySymbol firstSymbol = doc.GetElement(firstId) as FamilySymbol;
                    if (!firstSymbol.IsActive) firstSymbol.Activate();
                    return firstSymbol;
                }
            }

            return null;
        }
    }

    public sealed class ExtractedPointMap : ClassMap<ExtractedPoint>
    {
        public ExtractedPointMap()
        {
            // Map indexes based on what the Civil 3D extraction produces
            Map(m => m.X).Index(0);
            Map(m => m.Y).Index(1);
            Map(m => m.Z).Index(2);
            Map(m => m.RotationAngle).Index(3).Optional();
            Map(m => m.ParameterValue).Index(4).Optional();
        }
    }
}
